# Generated by Django 5.1.1 on 2024-09-22 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Id_producto',
            new_name='id_producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='Id_negocio',
        ),
        migrations.AlterField(
            model_name='negocio',
            name='logo_negocio',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='numero_de_local',
            field=models.CharField(max_length=50, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=1000, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='administrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_administrador', to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_cliente', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.AddField(
            model_name='producto',
            name='id_negocio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.negocio', verbose_name='Id Negocio'),
            preserve_default=False,
        ),
    ]
